services:
    bb3mobi.washere.helper:
        class: bb3mobi\washere\core\who_was_here
        arguments:
            - @template
            - @config
            - @user
            - @auth
            - @cache.driver
            - @dbal.conn
            - %core.table_prefix%
    bb3mobi.washere.listener:
        class: bb3mobi\washere\event\listener
        arguments:
            - @bb3mobi.washere.helper
        tags:
            - { name: event.listener }
